#!/usr/bin/env php
<?php

use Jbtronics\SettingsBundle\Tests\TestApplication\Kernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\ErrorHandler\Debug;

set_time_limit(0);

require_once dirname(__DIR__).'/../vendor/autoload.php';


$_ENV['ENV_VALUE2'] = "true";
$_SERVER['ENV_VALUE3'] = "12";

$input = new ArgvInput();

if ($_SERVER['APP_DEBUG'] ?? true) {
    umask(0000);

    if (class_exists(Debug::class)) {
        Debug::enable();
    }
}

if (null !== $env = $input->getParameterOption(['--env', '-e'], null, true)) {
    putenv('APP_ENV='.$_SERVER['APP_ENV'] = $_ENV['APP_ENV'] = $env);
}

if ($input->hasParameterOption('--no-debug', true)) {
    putenv('APP_DEBUG='.$_SERVER['APP_DEBUG'] = $_ENV['APP_DEBUG'] = '0');
}


$kernel = new Kernel($_SERVER['APP_ENV'] ?? 'test', (bool) ($_SERVER['APP_DEBUG'] ?? true));
$application = new Application($kernel);
$application->run($input);